// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyddezobhbkkcdpbjufw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5ZGRlem9iaGJra2NkcGJqdWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTkyNzUsImV4cCI6MjA2NzI3NTI3NX0.uPyef3Qr9cKeLsDqsAHLH-cJU6xt_IR4_64nR9K6hjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});